name: Linux builds

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  WXWIDGETS_ROOT: ${{ github.workspace }}/ext/wxWidgets
  WXWIN: ${{ github.workspace }}/ext/wxWidgets/install
  WXRUBY_RELEASE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            gtk_version: 2
            CC: gcc-7
            CXX: g++-7
            ruby: '2.5'
            wxWidgets: '3.2.1'
            swig: '3'
            configure_flags:
            use_xvfb: true
          - os: ubuntu-18.04
            gtk_version: 2
            CC: gcc-9
            CXX: g++-9
            ruby: '3.2'
            wxWidgets: '3.2.1'
            swig: '3'
            configure_flags:
            use_xvfb: true
          - os: ubuntu-20.04
            gtk_version: 3
            CC: gcc-9
            CXX: g++-9
            ruby: '2.5'
            wxWidgets: '3.2.1'
            swig: '4'
            configure_flags:
            use_xvfb: true
          - os: ubuntu-20.04
            gtk_version: 3
            CC: gcc-10
            CXX: g++-10
            ruby: '3.2'
            wxWidgets: '3.2.1'
            swig: '4'
            configure_flags:
            use_xvfb: true
          - os: ubuntu-22.04
            gtk_version: 3
            CC: gcc-11
            CXX: g++-11
            ruby: '3.0'
            wxWidgets: '3.2.1'
            swig: '4'
            configure_flags:
            use_xvfb: true
          - os: ubuntu-22.04
            gtk_version: 3
            CC: gcc-12
            CXX: g++-12
            ruby: '3.2'
            wxWidgets: '3.2.1'
            swig: '4'
            configure_flags:
            use_xvfb: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.CXX }} ruby-${{ matrix.ruby }} wxWidgets-${{ matrix.wxWidgets }} SWIG{{ matrix.swig }}
    env:
      wxGTK_VERSION: ${{ matrix.gtk_version && matrix.gtk_version || 3 }}
      wxCONFIGURE_FLAGS: ${{ matrix.configure_flags }}
      wxUSE_ASAN: ${{ matrix.use_asan && 1 || 0 }}
      wxUSE_XVFB: ${{ matrix.use_xvfb && 1 || 0 }}
      WX_EXTRA_PACKAGES: doxygen
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
    - name: Checkout wxRuby3
      uses: actions/checkout@v3

    - name: checkout wxWidgets
      uses: actions/checkout@v3
      with:
        repository: wxWidgets/wxWidgets
        path: ${{ env.WXWIDGETS_ROOT }}
        ref: v${{ matrix.wxWidgets }}
        submodules: 'recursive'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Set up build environment
      run: |
        # Install locales used by our tests to run all the tests instead of
        # skipping them.
        sudo locale-gen de_DE.utf8 de_CH.utf8 en_US.utf8 fr_FR.utf8 sv_SE.utf8
        
        $WXWIDGETS_ROOT/build/tools/before_install.sh

    - name: Display build environment
      run: |
        echo $PATH
        ruby -v
        doxygen -V
        gcc -v
        g++ -v

    - name: Configuring wxWidgets
      run: |
        wxCONFIGURE_OPTIONS="$wxCONFIGURE_FLAGS"
        if [ -n "${{ matrix.gtk_version }}" ]; then
          wxCONFIGURE_OPTIONS="--with-gtk=${{ matrix.gtk_version }} $wxCONFIGURE_OPTIONS"
        fi
        pushd $WXWIDGETS_ROOT
        ./configure $wxCONFIGURE_OPTIONS --prefix=$WXWIN --disable-tests --without-subdirs --disable-debug_info || rc=$?
        popd
        if [ -n "$rc" ]; then
          echo '*** Configuring failed, contents of config.log follows: ***'
          echo '-----------------------------------------------------------'
          cat $WXWIDGETS_ROOT/config.log
          echo '-----------------------------------------------------------'
          exit $rc
        fi

    - name: Build wxWidgets
      run: |
        pushd $WXWIDGETS_ROOT
        make && make install
        popd

    - name: Bootstrap wxRuby3
      run: |
        bundle exec rake bootstrap

    - name: Build wxRuby3
      run: |
        bundle exec rake -m

    - name: Run wxRuby3 regression tests
      run: |
        ulimit -c unlimited
        /bin/bash -o pipefail -c "xvfb-run -a -s '-screen 0 1600x1200x24' bundle exec rake wxtest 2>&1 | tee -a wxtest.out" || rc=$?
        if [ -n "$rc" ]; then
          if fgrep -q '(core dumped)' wxtest.out; then
            echo '*** Test crashed, trying to get more information ***'
            gdb --quiet --core=core -ex 'where' -ex 'thread apply all bt' -ex 'q' --args bundle exec rake wxtest
          fi
        exit $rc
        fi
