# CI workflow building wxRuby3 under Windows.
name: MSW builds

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOXYGEN_ROOT: ${{ github.workspace }}\doxygen
  WXWIDGETS_ROOT: ${{ github.workspace }}\ext\wxWidgets
  WXWIN: ${{ github.workspace }}/ext/wxWidgets/install
  WXRUBY_RELEASE: 1

jobs:
  build:
    runs-on: windows-${{ matrix.os }}
    name: wxMSW ${{ matrix.os }} Ruby ${{ matrix.ruby }} wxWidgets ${{ matrix.wxWidgets }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - os: windows-2022
#            platform: 'x64'
#            ruby: '3.2'
#            wxWidgets: '3.1.5'
#          - os: windows-2022
#            platform: 'x64'
#            ruby: '2.7'
#            wxWidgets: '3.1.5'
#          - os: windows-2022
#            platform: 'x64'
#            ruby: '2.7'
#            wxWidgets: '3.2.1'
          - os: windows-2022
            platform: 'x64'
            ruby: '3.2'
            wxWidgets: '3.2.1'

    steps:
      - name: Checkout wxRuby3
        uses: actions/checkout@v3
      - name: checkout wxWidgets
        uses: actions/checkout@v3
        with:
          repository: wxWidgets/wxWidgets
          path: ${{ env.WXWIDGETS_ROOT }}
          ref: v${{ matrix.wxWidgets }}
          submodules: 'recursive'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Download Doxygen tool
        run: wget.exe https://www.doxygen.nl/files/doxygen-1.9.6.windows.x64.bin.zip

      - name: Expand Doxygen package
        run: Expand-Archive -LiteralPath '.\doxygen-1.9.6.windows.x64.bin.zip' -DestinationPath ${{ env.DOXYGEN_ROOT }} -Force

      - name: Configuring wxWidgets
        run: |
          cd ${{ env.WXWIDGETS_ROOT }}
          ridk exec bash './configure --prefix=${{ env.WXWIN }} --disable-tests --without-subdirs --disable-debug_info'
