# CI workflow building wxRuby3 under Windows.
name: MSW builds

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOXYGEN_ROOT: ${{ github.workspace }}\doxygen
#  WXWIDGETS_ROOT: ${{ github.workspace }}\ext\wxWidgets
#  WXWIN_ROOT: ${{ github.workspace }}/ext/wxWidgets/install
#  WXRUBY_RELEASE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: wxMSW ${{ matrix.os }} ${{ matrix.CXX }} Ruby-${{ matrix.ruby }} wxWidgets-${{ matrix.wxWidgets }} SWIG${{ matrix.swig }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - os: windows-2022
#            platform: 'x64'
#            ruby: '3.2'
#            wxWidgets: '3.1.5'
#            swig: '4'
#          - os: windows-2022
#            platform: 'x64'
#            ruby: '2.7'
#            wxWidgets: '3.1.5'
#            swig: '4'
          - os: windows-2022
            platform: 'x64'
            CXX: g++-12
            ruby: '2.7'
            wxWidgets: '3.2.1'
            swig: '4'
          - os: windows-2022
            platform: 'x64'
            CXX: g++-12
            ruby: '3.2'
            wxWidgets: '3.2.1'
            swig: '4'

    steps:
      - name: Checkout wxRuby3
        uses: actions/checkout@v3
#      - name: checkout wxWidgets
#        uses: actions/checkout@v3
#        with:
#          repository: wxWidgets/wxWidgets
#          path: ${{ env.WXWIDGETS_ROOT }}
#          ref: v${{ matrix.wxWidgets }}
#          submodules: 'recursive'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Download Doxygen tool
        run: wget.exe https://www.doxygen.nl/files/doxygen-1.9.6.windows.x64.bin.zip

      - name: Install Doxygen package
        run: |
          Expand-Archive -LiteralPath '.\doxygen-1.9.6.windows.x64.bin.zip' -DestinationPath $env:DOXYGEN_ROOT -Force
          echo "$env:DOXYGEN_ROOT" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Display build environment
        run: |
          echo "$env:PATH"
          ruby -v
          doxygen -v
          ridk exec bash -c 'gcc -v'
          ridk exec bash -c 'g++ -v'

#      - name: Configuring wxWidgets
#        run: |
#          Push-Location $env:WXWIDGETS_ROOT
#          ridk exec bash -c './configure --prefix=`pwd`/install --disable-tests --without-subdirs --disable-debug_info'
#          Pop-Location
#
#      - name: Build wxWidgets
#        run: |
#          Push-Location $env:WXWIDGETS_ROOT
#          ridk exec bash -c 'make && make install'
#          Pop-Location

      - name: Configure wxRuby3
        run: |
          bundle exec rake configure[--with-wxwin]

      - name: Build wxRuby3
        run: |
          bundle exec rake build

      - name: Run wxRuby3 regression tests
        run: |
          bundle exec rake test
